-- Useful plugin to show pending keybinds
return {
	"folke/which-key.nvim",
	event = "VimEnter", -- Sets the loading event to 'VimEnter'
	opts = {
		delay = 0,
		icons = {
			mappings = vim.g.have_nerd_font,
			keys = vim.g.have_nerd_font and {} or {
				Up = "<Up> ",
				Down = "<Down> ",
				Left = "<Left> ",
				Right = "<Right> ",
				C = "<C-…> ",
				M = "<M-…> ",
				D = "<D-…> ",
				S = "<S-…> ",
				CR = "<CR> ",
				Esc = "<Esc> ",
				ScrollWheelDown = "<ScrollWheelDown> ",
				ScrollWheelUp = "<ScrollWheelUp> ",
				NL = "<NL> ",
				BS = "<BS> ",
				Space = "<Space> ",
				Tab = "<Tab> ",
				F1 = "<F1>",
				F2 = "<F2>",
				F3 = "<F3>",
				F4 = "<F4>",
				F5 = "<F5>",
				F6 = "<F6>",
				F7 = "<F7>",
				F8 = "<F8>",
				F9 = "<F9>",
				F10 = "<F10>",
				F11 = "<F11>",
				F12 = "<F12>",
			},
		},

		-- Document existing key chains
		spec = {
			{ "<leader>c", group = "Code", mode = { "n", "x" } },
			{ "<leader>q", group = "Diagnostics" },
			{ "<leader>d", group = "Debug/Document" },
			{ "<leader>r", group = "Rename" },
			{ "<leader>f", group = "Find" },
			{ "<leader>w", group = "Workspace" },
			{ "<leader>t", group = "Test/Toggle" },
			{ "<leader>ts", desc = "Toggle Settings" },
			{ "<leader>b", group = "Buffer/Debug" },
			{ "<leader>bp", desc = "Toggle Pin Buffer" },
			{ "<leader>bP", desc = "Delete Non-Pinned Buffers" },
			{ "<leader>br", desc = "Delete Buffers to the Right" },
			{ "<leader>bl", desc = "Delete Buffers to the Left" },
			{ "<leader>g", group = "Git" },
			{ "<leader>gb", desc = "Git Blame Line" },
			{ "<leader>gB", desc = "Git Browse" },
			{ "<leader>gf", desc = "Git File History" },
			{ "<leader>gl", desc = "Git Log" },
			{ "<leader>gg", desc = "Lazygit" },
			{ "<leader>gh", group = "Git Hunk" },
			{ "<leader>e", group = "Explorer" },
			{ "<leader>s", group = "Search/Format" },
			{ "<leader>S", group = "Scratch Buffer" },
			{ "<leader>x", group = "Trouble" },
			{ "<leader>T", group = "Terminal" },
			{ "<leader>n", desc = "Notification History" },
			-- Buffer navigation
			{ "<S-h>", desc = "Previous Buffer" },
			{ "<S-l>", desc = "Next Buffer" },
			{ "[b", desc = "Previous Buffer" },
			{ "]b", desc = "Next Buffer" },
			{ "[B", desc = "Move Buffer Left" },
			{ "]B", desc = "Move Buffer Right" },
			-- Terminal
			{ "<c-/>", desc = "Toggle Terminal" },
			-- Noice scrolling
			{ "<c-f>", desc = "Scroll Forward (LSP)", mode = { "i", "n", "s" } },
			{ "<c-b>", desc = "Scroll Backward (LSP)", mode = { "i", "n", "s" } },
			-- Command mode
			{ "<S-Enter>", desc = "Redirect Cmdline", mode = "c" },
		},
	},
}
